### ISSUE TITLE
cross site request not allowed (csrf)

### ISSUE THREAD

**Issue by came** [Tivix/angular-django-registration-auth#11]
I am evaluating angular-django-registration-auth in conjunction with django-rest-auth. 
When I try to call the login API within angular-django-registration-auth I get the UI error: "Could not connect. Please try again."
Locking into the browser console I see: 
XMLHttpRequest cannot load http://127.0.0.1:8000/rest-auth/login/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:9002' is therefore not allowed access.
djangoAuth.js:43 error syncing with: http://127.0.0.1:8000/rest-auth/login/

the response header looks like:
HTTP/1.0 200 OK
Date: Fri, 23 Jan 2015 10:27:25 GMT
Server: WSGIServer/0.1 Python/2.7.6
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN
Content-Type: application/json
Allow: POST, OPTIONS

I guess this has something to do with csrf but I cannot figure out what I need to change either in the client $http request or on django view site. 
Besides, using the browseable API of DRF it works.

Any clues, ideas what I should look for?
BR

**Comment by petershafer** [comment]
Hi Carsten,

Right now you're seeing the response to an HTTP OPTIONS request.  Since you're running the web page from port 9002 and rest-auth is running from port 8000, the browser considers it a cross-domain request.  So it sends this "pre-flight" request to ask the server if it will respond to cross-domain requests.  The response indicates that it only allows HTTP POST and OPTIONS requests to be made to Django.

When code is in production, serving everything from the same port is easier, but during development we've had to work around this issue so that we wouldn't be relying on Django to manage the AngularJS assets for us instead of grunt.  What you can do is utilize the django-cors-headers package in your project to enable cross domain requests.  This requires a bit more configuration.  Below is a sample configuration I use.

INSTALLED_APPS.append('corsheaders')
MIDDLEWARE_CLASSES.append('corsheaders.middleware.CorsMiddleware')
CORS_ORIGIN_WHITELIST = ('127.0.0.1:9000',)
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
CORS_ALLOW_HEADERS = (
        'x-requested-with',
        'content-type',
        'accept',
        'origin',
        'authorization',
        'x-csrftoken',
        'Api-Authorization',
    )

Something to keep in mind with this approach is that you will not be able to use cookies.  This may be a deal breaker for you if you're not using token based authentication (which can be managed via HTTP headers instead of cookies.)

That should help get things moving.

Cheers!

**Comment by dtromblee** [comment]
Peter, 

Thanks for taking the time to explain that. I know that's a super common issue, but my team really needed a leg up in understanding authentication, and we encountered the same error. 

Given the lack of solid examples of angular for these more complex processes, this is really a godsend.

**Comment by petershafer** [comment]
Glad to hear it's been helpful to your team, @dtromblee!
